version: '2'


services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
     MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - my-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - my-network
  node:
    build: victor
    command: npm start
    ports:
      - "9010:9010"
    volumes:
      - .:/user/app
    restart: always
    networks:
      - my-network
networks:
  my-network: